server:
  port: 8080

spring:
  freemarker:
    prefix: classpath:/templates/
  mvc:
    servlet:
      load-on-startup: 0

jndi:
  type: ldap
  ip: 127.0.0.1
  ldap:
    port: 1389
    base: dc=example,dc=com
  rmi:
    port: 1099